distros:
  - el7
  - fc26
substage:
  - a:
      script:
        fromfile: check-patch.sh
  - b:
      script: |
        #!/bin/bash
        echo "THIS IS A TEST FOR SUBSTAGES"
release_branches:
  master: dummy-master
  'v1.0': dummy-1.0
